# Generated by Django 4.2.6 on 2023-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happytailsapp', '0006_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='addyours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petImage', models.ImageField(upload_to='uploads/')),
                ('petName', models.TextField()),
                ('petWeight', models.TextField()),
                ('petBreed', models.TextField()),
                ('vaccinationStatus', models.CharField(choices=[('vaccinated', 'Vaccinated'), ('notVaccinated', 'Not Vaccinated'), ('Unknown', 'Unknown')], default='Unknown', max_length=15)),
            ],
        ),
    ]
