# Generated by Django 4.2.6 on 2023-12-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happytailsapp', '0007_addyours'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('residence_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo')], max_length=20)),
                ('exercise_plan', models.TextField()),
                ('hours_alone', models.PositiveIntegerField()),
                ('previous_pets', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
