# Generated by Django 4.2.6 on 2023-12-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happytailsapp', '0008_adoptionapplication_alter_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionapplication',
            old_name='full_name',
            new_name='name',
        ),
    ]
