# Generated by Django 4.2.6 on 2023-12-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happytailsapp', '0009_rename_full_name_adoptionapplication_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionapplication',
            old_name='exercise_plan',
            new_name='exercisePlan',
        ),
        migrations.RenameField(
            model_name='adoptionapplication',
            old_name='hours_alone',
            new_name='hoursAlone',
        ),
        migrations.RenameField(
            model_name='adoptionapplication',
            old_name='previous_pets',
            new_name='previousPets',
        ),
        migrations.RenameField(
            model_name='adoptionapplication',
            old_name='residence_type',
            new_name='residenceType',
        ),
    ]
