# Generated by Django 4.2.6 on 2023-12-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happytailsapp', '0010_rename_exercise_plan_adoptionapplication_exerciseplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='category',
            field=models.CharField(default='street', max_length=255),
        ),
    ]
