# Generated by Django 4.2.6 on 2023-12-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happytailsapp', '0016_adoptionapplication_adopted_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionapplication',
            name='adopted_animal',
        ),
    ]
