# Generated by Django 4.2.6 on 2023-12-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happytailsapp', '0017_remove_adoptionapplication_adopted_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
